services:
  cassandra:
    image: cassandra:5.0-jammy   # better to use a specific version, if you want to control upgrades
    container_name: cass1
    hostname: cass1
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - cassandra
    ports:
      - "9042:9042"  # Expose native binary CQL port for your apps
    volumes:
      - ./data/cass1:/var/lib/cassandra    # This is the volume that will persist data for cass1 node
      - ./etc/cass1:/etc/cassandra   # Use your own config files for full control
      - ./cassandra-dc-1:/usr/local/bin/
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
    environment: &environment    # Declare and save environments variables into "environment"
      CASSANDRA_SEEDS: "cass1,cass2"    # The first two nodes will be seeds
      CASSANDRA_CLUSTER_NAME: SolarSystem
      CASSANDRA_DC: Mars
      CASSANDRA_RACK: West
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
networks:
  cassandra:
